env:
  global:
    - secure: eRaW2KaFk7qBAt+SmThX0aJHtkAeaTi2eQV/LEuK5wR5AueeeJowoKm61tEjQfgjBReVKYUaTox/aDe0Dzfi2+b9EpXq7rC1i/cpJ7yE7l+s6qyugpDNW60GViIW+OpsDRmKlbOKIkuYXoKkCENUNGTum8xkNuGfPn+vmKWxekKMY7eD21p8f3XT/FwktUUsIsouapi9ZcMZZIYy2tQsGZq3HKb1Xfcu2xcPWq65tdyp89XQUlTV+1qPnRaSenfrdqim0qBWxp3epyUnp8rnjLeLelfcliuKgvOLhZyXgxq87uRUxsPKQ5qtSzmXIfCVk4Q9WSSvUr4yUAqNHYH5DCRXprypHVZGiH439H/gWTHsfMjJ/ahXvUJqajCgjn/vIZCbdy7QTWy6tARmAwJp7Zb3bsOgCDm2DlOHJovlX+iPRnEDfN4pWahBLd2XJlivrzs+IL7BwvC8wTUJudRbj9otwDhWhSBbecPMJrAURzUL7ooSU28Rvutk7tOe1Ipr74LHvJTSb0DI8e1Ed7Q35aQ2xYuFDkYOfFDlK5YFDPzDQRgF+ChOuS+PcEprNeC/JYmOrYdboyxL17oZSNQGZmmBLOCF2xtKQTeVMX4jJxGt/ybnSUL0nGIDysCFtADqawyVf0Iy8OSrqwFylY/zhpAyfQ/v3SmPWf6fnqZehmM=
language: rust
script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
after_script:
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
