env:
  global:
    - secure: e/HQwqp86vDWpfZ+hdL9D39y6O5yktEbWPU8FKt84qLiOO3IJ02KzKycRfiWJbPreX4d9i599JmFFKRKS0pFjqSX8esckEnl1yuzfNXcOn2NSlF6V/9HZbJa1jUiB83tU0h1TxhfB1zzGltjbCJwdtD4Y9J6NkD7FEYFmwmVSfeOfYAU4v8AlZKCpK76mufZjPnZinFyauuTa8xrfvVyrVnFiEsx41O3GqRaftNbFn40xzM4oYTIDFHkjX6iHCKhmb+WTAnElL5bUanZlXyrU3CyHogYT8M1mpOP2JdBRDPfu2lRzBPCT/590d9cpf4kha/77ZB4/ZMgbRQeRf4qTGFwpuR9rn5ntPp79bVR+eOfuhUTtbkrCM9noTP0bQdFGwuY1OiCqYuWGheXvFRiBFPChBscplR2Pl7D4RyRjh7C32DyAnOaVfIdQkjikNuTc47xyWSTroDlu37Tjd378fcPo73Snn5g9bGBqK+HBL47ISkzinN12mWwZCWRqKhUkrhdh9e8OMFjDNa+2cGB6xyVBnguUJDVVAjYgObC6tJlCcPqKNQn6deLa5PhPY4uamAokCytdfNLVuNO5Wvb8Xfnf4LpC9lK6frIcGVjBET5EEKue/A82QyG2/66deN1WuiLHjFsyY+ScEbTeFQW+WZqztQeJ4lP7VxWuWO2fDo= 
language: rust
script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
after_script:
  - mv target/doc doc
  - echo | curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN
